# Generated by Django 5.2.8 on 2025-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=12)),
                ('asof', models.DateTimeField(auto_now=True)),
                ('tech_score', models.FloatField(default=0.0)),
                ('fundamental_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('components', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
