# Generated by Django 5.2.8 on 2025-11-13 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0002_watchlist_watchlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('symbol', 'Single symbol'), ('watchlist', 'Watchlist')], default='symbol', max_length=16)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('min_final_score', models.FloatField()),
                ('min_tech_score', models.FloatField(blank=True, null=True)),
                ('min_fund_score', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('trigger_once', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ranker.watchlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
