# Generated by Django 5.2.8 on 2025-11-14 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0003_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tech_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fund_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ranker.alert')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
