# Generated by Django 5.2.8 on 2025-11-14 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0004_alertevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tickers', models.CharField(blank=True, help_text='Comma-separated symbols, e.g. AAPL,MSFT,NVDA', max_length=512)),
                ('default_tech_weight', models.FloatField(default=0.6)),
                ('default_fund_weight', models.FloatField(default=0.4)),
                ('default_min_final_score', models.FloatField(default=15.0, help_text='Default alert threshold for final score')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockranker_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
