# Generated by Django 5.2.8 on 2025-11-16 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0005_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('tickers', models.JSONField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('benchmark', models.CharField(default='SPY', max_length=16)),
                ('initial_capital', models.FloatField()),
                ('rebalance_days', models.PositiveIntegerField(default=5)),
                ('top_n', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
