# Generated by Django 5.2.8 on 2025-11-16 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0006_backtestrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tickers', models.TextField(help_text='Comma-separated tickers')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('initial_capital', models.FloatField(default=10000.0)),
                ('rebalance_days', models.PositiveIntegerField(default=5)),
                ('top_n', models.PositiveIntegerField(blank=True, null=True)),
                ('benchmark', models.CharField(default='SPY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
