# Generated by Django 5.2.8 on 2025-11-17 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0007_backtestconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_scan_enabled', models.BooleanField(default=False)),
                ('daily_scan_min_score', models.FloatField(default=15.0)),
                ('daily_scan_max_ideas', models.PositiveIntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranker_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
