# Generated by Django 5.2.8 on 2025-11-18 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0008_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='initial_capital',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='backtestrun',
            name='summary',
            field=models.JSONField(default=dict),
        ),
    ]
