# Generated by Django 5.2.8 on 2025-11-22 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranker", "0012_botconfig_strategyspec"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("stopped", "Stopped"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                        ],
                        default="stopped",
                        max_length=16,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("backtest", "Backtest"),
                            ("paper", "Paper"),
                            ("live", "Live"),
                        ],
                        default="backtest",
                        max_length=16,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("1m", "Every minute"),
                            ("5m", "Every 5 minutes"),
                            ("15m", "Every 15 minutes"),
                            ("1h", "Hourly"),
                            ("1d", "Daily"),
                        ],
                        default="5m",
                        max_length=16,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bots",
                        to="ranker.botconfig",
                    ),
                ),
                (
                    "strategy_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bots",
                        to="ranker.strategyspec",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
