# Generated by Django 6.1.1 on 2026-09-23 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0028_expired_terminal_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_run_at', models.DateTimeField(unique=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, choices=[('premarket', 'Premarket'), ('regular', 'Regular session'), ('aftermarket', 'Aftermarket'), ('market_closed', 'Market closed')], default='', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('publication', 'Publication'), ('cancellation', 'Cancellation'), ('watchlist_no_trade', 'Watchlist / no trade'), ('failure', 'Failure')], default='', max_length=24)),
                ('market_regime', models.CharField(blank=True, default='', max_length=80)),
                ('candidates_reviewed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('operator_action', models.CharField(blank=True, default='', max_length=120)),
                ('verified_result', models.CharField(blank=True, default='', max_length=500)),
                ('error_summary', models.CharField(blank=True, default='', max_length=500)),
                ('next_expected_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expected_run_at'],
            },
        ),
        migrations.AlterField(
            model_name='operationaltelegramalert',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_alerts', to='ranker.tradesignal'),
        ),
    ]
