# Generated by Django 6.1.1 on 2026-09-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0029_research_run_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=80, unique=True)),
                ('decision', models.JSONField()),
                ('category', models.CharField(choices=[('near_miss', 'Near miss'), ('index', 'Index benchmark')], max_length=16)),
                ('rejection_reason', models.CharField(blank=True, choices=[('no_fresh_catalyst', 'No Fresh Catalyst'), ('extended', 'Extended'), ('wide_spread', 'Wide Spread'), ('low_volume', 'Low Volume'), ('low_open_interest', 'Low Open Interest'), ('insufficient_confirmation', 'Insufficient Confirmation'), ('marginal_reward_risk', 'Marginal Reward Risk'), ('uncertain_flow', 'Uncertain Flow'), ('earnings_proximity', 'Earnings Proximity'), ('contract_data_unavailable', 'Contract Data Unavailable'), ('other', 'Other')], max_length=40)),
                ('execution_mode', models.CharField(choices=[('observation', 'Observation only'), ('broker_intended', 'Broker intended')], default='observation', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('expired_unfilled', 'Expired Unfilled'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='proposed', max_length=24)),
                ('ruleset_version', models.CharField(max_length=32)),
                ('broker_account_id', models.CharField(blank=True, max_length=80)),
                ('broker_entry_order_id', models.CharField(blank=True, max_length=80)),
                ('broker_exit_order_id', models.CharField(blank=True, max_length=80)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('research_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shadow_setups', to='ranker.researchrun')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('broker_order_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ranker.shadowsetup')),
            ],
        ),
    ]
