# Generated by Django 6.1.1 on 2026-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0030_shadowsetup_shadowevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowExecutorHealth',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('status', models.CharField(default='disabled', max_length=24)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('verified_account_id', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shadowsetup',
            name='broker_entry_client_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shadowsetup',
            name='broker_exit_client_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shadowsetup',
            name='broker_protection_kind',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='shadowsetup',
            name='contract_symbol',
            field=models.CharField(db_index=True, default='', max_length=21),
        ),
        migrations.AddField(
            model_name='shadowsetup',
            name='last_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='shadowsetup',
            name='trigger_first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
