# Generated by Django 6.1.1 on 2026-09-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0032_shadow_immutability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadowsetup',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('expired_unfilled', 'Expired Unfilled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='proposed', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='shadowsetup',
            constraint=models.UniqueConstraint(
                fields=('contract_symbol',),
                condition=models.Q(status__in=['proposed', 'waiting', 'active']),
                name='unique_active_shadow_contract',
            ),
        ),
    ]
