# Generated by Django 6.1.1 on 2026-09-27 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0034_telegram_notification_skipped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaperConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpaca_account_id', models.CharField(max_length=80, unique=True)),
                ('encrypted_access_token', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_paper_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
