# Generated by Django 6.1.1 on 2026-09-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0035_customer_paper_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaperconnection',
            name='auth_method',
            field=models.CharField(default='oauth', max_length=12),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='max_open_positions',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='max_trade_notional',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='mirror_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpaperconnection',
            name='trading_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomerPaperExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='mirror', max_length=12)),
                ('state', models.CharField(db_index=True, default='entry_intent', max_length=24)),
                ('symbol', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('entry_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('exit_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('exit_kind', models.CharField(blank=True, default='', max_length=12)),
                ('exit_generation', models.PositiveIntegerField(default=0)),
                ('entry_attempted', models.BooleanField(default=False)),
                ('exit_attempted', models.BooleanField(default=False)),
                ('missing_position_since', models.DateTimeField(null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('entry_fill', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('exit_fill', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('order_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('checked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='ranker.customerpaperconnection')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_executions', to='ranker.tradesignal')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPaperEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ranker.customerpaperconnection')),
                ('execution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ranker.customerpaperexecution')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customerpaperexecution',
            constraint=models.UniqueConstraint(fields=('connection', 'signal'), name='customer_paper_signal_once'),
        ),
    ]
