# Generated by Django 5.2.8 on 2025-11-19 20:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=18)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=18)),
                ('equity', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='paper.paperportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_public_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_amount', 'Trailing Stop (Amount)'), ('trailing_percent', 'Trailing Stop (Percent)'), ('bracket', 'Bracket'), ('oco', 'One Cancels Other')], max_length=16)),
                ('tif', models.CharField(choices=[('day', 'DAY'), ('gtc', 'GTC'), ('ioc', 'IOC'), ('fok', 'FOK')], max_length=8)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notional', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('trail_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('trail_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('working', 'WORKING'), ('part_filled', 'PARTIALLY_FILLED'), ('filled', 'FILLED'), ('canceled', 'CANCELED'), ('expired', 'EXPIRED'), ('rejected', 'REJECTED')], default='new', max_length=24)),
                ('filled_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('average_fill_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='paper.paperorder')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='paper.paperportfolio')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper.strategy')),
            ],
        ),
    ]
