# Generated by Django 5.2.8 on 2025-11-19 20:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paperorder',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('working', 'WORKING'), ('part_filled', 'PARTIALLY FILLED'), ('filled', 'FILLED'), ('canceled', 'CANCELED'), ('expired', 'EXPIRED'), ('rejected', 'REJECTED')], default='new', max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='paperposition',
            unique_together={('portfolio', 'symbol')},
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=32)),
                ('period', models.CharField(default='since_join', max_length=16)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='paper.paperportfolio')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='paper.leaderboardseason')),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('slippage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='paper.paperorder')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='paper.paperportfolio')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('logic', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='paper.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(default=dict)),
                ('generated_orders', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], default='success', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_logs', to='paper.paperportfolio')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='paper.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('equity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('leverage', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='paper.paperportfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'timestamp')},
            },
        ),
    ]
