# Generated by Django 5.2.8 on 2025-11-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_leaderboardseason_alter_paperorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperorder',
            name='condition_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('price', 'Price Trigger'), ('time', 'Time Trigger'), ('indicator', 'Indicator Trigger'), ('cross_symbol', 'Cross Symbol'), ('volume', 'Volume Trigger')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='extended_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='pegged_offset',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='reserve_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='tif_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paperorder',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_amount', 'Trailing Stop (Amount)'), ('trailing_percent', 'Trailing Stop (Percent)'), ('trailing_limit', 'Trailing Stop Limit'), ('market_close', 'Market on Close'), ('market_open', 'Market on Open'), ('limit_close', 'Limit on Close'), ('limit_open', 'Limit on Open'), ('pegged_mid', 'Pegged to Midpoint'), ('pegged_primary', 'Primary Peg'), ('hidden_limit', 'Hidden Limit'), ('iceberg', 'Iceberg / Reserve'), ('bracket', 'Bracket Entry'), ('oco', 'One Cancels Other'), ('oto', 'One Triggers Other'), ('otoco', 'One Triggers OCO')], max_length=16),
        ),
        migrations.AlterField(
            model_name='paperorder',
            name='tif',
            field=models.CharField(choices=[('day', 'DAY'), ('gtc', 'GTC'), ('gtd', 'GTD'), ('ioc', 'IOC'), ('fok', 'FOK'), ('aon', 'All or None'), ('opg', 'On Open'), ('cls', 'At Close'), ('ext', 'Extended Hours')], default='day', max_length=8),
        ),
    ]
