# Generated by Django 5.2.8 on 2025-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_paperorder_condition_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperorder',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('price', 'Price Trigger'), ('time', 'Time Trigger'), ('indicator', 'Indicator Trigger'), ('cross_symbol', 'Cross Symbol'), ('volume', 'Volume Trigger'), ('and_group', 'AND Group'), ('or_group', 'OR Group')], default='none', max_length=32),
        ),
    ]
