# Generated by Django 5.2.8 on 2025-11-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_alter_paperorder_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperorder',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_amount', 'Trailing Stop (Amount)'), ('trailing_percent', 'Trailing Stop (Percent)'), ('trailing_limit', 'Trailing Stop Limit'), ('market_close', 'Market on Close'), ('market_open', 'Market on Open'), ('limit_close', 'Limit on Close'), ('limit_open', 'Limit on Open'), ('pegged_mid', 'Pegged to Midpoint'), ('pegged_primary', 'Primary Peg'), ('hidden_limit', 'Hidden Limit'), ('iceberg', 'Iceberg / Reserve'), ('bracket', 'Bracket Entry'), ('oco', 'One Cancels Other'), ('oto', 'One Triggers Other'), ('otoco', 'One Triggers OCO'), ('algo_vwap', 'Algo VWAP'), ('algo_twap', 'Algo TWAP'), ('algo_pov', 'Algo Participation')], max_length=16),
        ),
    ]
