# Generated by Django 5.2.8 on 2025-11-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_alter_paperorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperorder',
            name='algo_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
