# Generated by Django 5.2.8 on 2025-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_paperorder_algo_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
