# Generated by Django 5.2.8 on 2025-11-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_strategy_last_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperorder',
            name='chain_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='child_role',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
