# Generated by Django 5.2.8 on 2025-11-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_paperorder_chain_id_paperorder_child_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperorder',
            name='algo_next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperorder',
            name='algo_slice_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
