# Generated by ChatGPT

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0009_paperorder_algo_next_run_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("exchange", models.CharField(blank=True, max_length=32)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("equity", "Equity"),
                            ("etf", "ETF"),
                            ("adr", "ADR"),
                            ("crypto", "Crypto"),
                            ("fx", "FX"),
                            ("bond", "Bond"),
                        ],
                        default="equity",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="paperportfolio",
            name="max_gross_exposure_pct",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="paperportfolio",
            name="max_positions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paperportfolio",
            name="max_single_position_pct",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="paperposition",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="paper.instrument",
            ),
        ),
        migrations.AddField(
            model_name="papertrade",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trades",
                to="paper.instrument",
            ),
        ),
        migrations.CreateModel(
            name="PortfolioResetLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reset_to", models.DecimalField(decimal_places=2, max_digits=18)),
                ("previous_cash", models.DecimalField(decimal_places=2, max_digits=18)),
                ("previous_equity", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_resets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_logs",
                        to="paper.paperportfolio",
                    ),
                ),
            ],
        ),
    ]
